### PR TITLE
Farming page

### PR DESCRIPTION
**Pull request by Mi-Lan**
Screenshot 2021-09-30 at 18 28 53
This is how it looks currently....It would be good if we can check data first and then when designs are ready I will update it to be much prettier then it is now.

### CODE REVIEW

**Comment by 0xVenky** [comment]
Just 3 comments, but this page would like some love from @zamli 

- We should only display active pairs, or have a column to say if its active, upcoming or expired ?
- We should display the total value staked in USD instead of TVL.
- Add a column about what token is rewarded.

**Comment by Mi-Lan** [comment]
> Just 3 comments, but this page would like some love from @zamli
> 
> * We should only display active pairs, or have a column to say if its active, upcoming or expired ?
> * We should display the total value staked in USD instead of TVL.
> * Add a column about what token is rewarded.
> 
> Functionality and calculations seem to work correctly. :)
Thanks for feedback!
1) Well currently Im displaying just campaigns that have more then 0 tokens staked regardless if they are active. Should I change it to just active? 
2) Okay will look into that more I think its easy fix of just calculating value of those staked tokens in usd...
3)Where would you suggest I add that? Just new column with only that info like icon and symbol?

**Comment by 0xVenky** [comment]
Looks great and we have all the details, final few comments and then this should be ready to merge

- Right align the value and left align the token name 
image

- Staked, in USD - move the column next to TVL

Great work @Mi-Lan ❤️  🚀

**Comment by 0xVenky** [comment]
This PR needs these to complete:
- Right align the value and left align the token name as per image in above comment
- Staked, in USD - move the column next to TVL
- Show only active campaigns
- A button, when clicked, will show all expired campaigns.

**Pull request merged**
