### PR TITLE
Feature/utilization 25

### PR DESCRIPTION
**Pull request by kliyer-ai**
Adds pool utilization to the detail view of a pair. 
image

Unfortunately, I wasn't yet able to also add it to the list view...

### CODE REVIEW

**Review by Mi-Lan — APPROVED** [review]
Awesome job! Couldn't find any issues with it! You did very good job of reusing stuff we already had and written it in accordance to rest of the code  🚀

**Comment by Mi-Lan** [comment]
Screenshot 2021-11-23 at 18 02 08
I think only suggestion I would have is for handling NaN like in this example so it doesn't fuckup the calcualtion here
Screenshot 2021-11-23 at 18 02 59

**Comment by kliyer-ai** [comment]
Yes, good catch! I'll change that.

**Comment by kliyer-ai** [comment]
@Mi-Lan I think this should fix the NaN issue because it was caused by a division by 0. Now `utilization` should always be defined.

**Review by Mi-Lan — APPROVED** [review]
GJ!

**Pull request merged**
